"""LaTeX result tables and the numbers.json digest used by the manuscript."""
from __future__ import annotations

import json
import os

import numpy as np
import pandas as pd

from ..config import (CODE_DIR, EVAL_DIR, HEADLINE_METHODS, HEADLINE_SEEDS,
                      RUNS_DIR, TRAIN_FAULT_TYPES, run_name)
from . import aggregate as agg

MS_DIR = os.path.normpath(os.path.join(CODE_DIR, "..", "manuscript"))

METHOD_TEX = {"raw_dr": "RAW-DR", "nom": "NOM", "dr": "DR",
              "teacher": "PROTEUS-T (oracle)", "proteus": "PROTEUS",
              "abl_unif": "A1 uniform severity", "abl_ddpg": "A5 DDPG",
              "abl_noflow": "A2 proprio-only", "abl_w5": "A3 $W{=}5$",
              "abl_ff": "A4 feed-forward", "abl_offline": "A6 offline"}
FT_TEX = {"gain_L": "Gain-L", "gain_R": "Gain-R", "bias": "Bias",
          "latency": "Latency", "slip": "Slip", "droop": "Droop"}


def _pm(mean, std, scale=100.0, d=1):
    import math
    if std is None or (isinstance(std, float) and math.isnan(std)):
        return f"{scale * mean:.{d}f}"          # single-seed: no spurious std
    return f"{scale * mean:.{d}f}$\\pm${scale * std:.{d}f}"


def tab_main(cells: pd.DataFrame, out="tab_main.tex") -> str:
    """Success rate at s in {1/3, 2/3, 1} per fault type + macro AUC."""
    auc = agg.auc_table(cells, "success")
    lines = [
        "% auto-generated by proteus.analysis.tables",
        "\\begin{table*}[!t]\\centering",
        "\\caption{Success rate [\\%] under persistent actuation faults at "
        "severity $s\\in\\{1/3,2/3,1\\}$ per fault type, and the macro "
        "success--severity AUC over all six trained fault axes "
        "(mean$\\pm$std over three seeds; forty episodes per cell).}",
        "\\label{tab:main}",
        "\\setlength{\\tabcolsep}{3.4pt}\\footnotesize",
        "\\begin{tabular}{l" + "ccc" * len(TRAIN_FAULT_TYPES) + "c}",
        "\\toprule",
        " & " + " & ".join(
            f"\\multicolumn{{3}}{{c}}{{{FT_TEX[ft]}}}"
            for ft in TRAIN_FAULT_TYPES) + " & Macro \\\\",
        "Method & " + " & ".join(
            ["$\\frac{1}{3}$ & $\\frac{2}{3}$ & $1$"] *
            len(TRAIN_FAULT_TYPES)) + " & AUC \\\\",
        "\\midrule",
    ]
    for m in HEADLINE_METHODS:
        cs = cells[cells.method == m]
        if cs.empty:
            continue
        row = [METHOD_TEX[m]]
        for ft in TRAIN_FAULT_TYPES:
            for si in (2, 4, 6):        # severities 1/3, 2/3, 1
                g = cs[(cs.fault_type == ft) & (cs.sev_idx == si)]
                p = g.groupby("seed")["success"].mean()
                row.append(f"{100 * p.mean():.0f}" if len(p) else "--")
        am = auc[(auc.method == m) & (auc.fault_type == "macro")]
        row.append(_pm(am["auc_success"].mean(), am["auc_success"].std(),
                       scale=100, d=1))
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    tex = "\n".join(lines)
    with open(os.path.join(MS_DIR, out), "w") as f:
        f.write(tex)
    print(f"[tab] {out}")
    return tex


def tab_ablation(cells_all: pd.DataFrame, out="tab_ablation.tex") -> str:
    methods = ["dr", "abl_unif", "abl_ddpg", "teacher", "abl_offline",
               "abl_ff", "abl_w5", "abl_noflow", "proteus"]
    auc_s = agg.auc_table(cells_all, "success")
    auc_c = agg.auc_table(cells_all, "collision")
    lines = [
        "% auto-generated by proteus.analysis.tables",
        "\\begin{table}[!t]\\centering",
        "\\caption{Ablations: macro success and collision AUC over the six "
        "trained fault axes, and mean context error where applicable "
        "(headline methods: three seeds; ablations: one seed).}",
        "\\label{tab:ablation}",
        "\\setlength{\\tabcolsep}{5pt}\\footnotesize",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Variant & AUC$_S$ $\\uparrow$ & AUC$_C$ $\\downarrow$ & "
        "$\\overline{\\|\\hat{c}-c\\|}$ $\\downarrow$ \\\\",
        "\\midrule",
    ]
    for m in methods:
        a_s = auc_s[(auc_s.method == m) & (auc_s.fault_type == "macro")]
        if a_s.empty:
            continue
        a_c = auc_c[(auc_c.method == m) & (auc_c.fault_type == "macro")]
        cs = cells_all[cells_all.method == m]
        ce = cs["c_err"].mean() if "c_err" in cs and cs["c_err"].sum() > 0 \
            else None
        row = [METHOD_TEX[m],
               _pm(a_s["auc_success"].mean(), a_s["auc_success"].std()),
               _pm(a_c["auc_collision"].mean(), a_c["auc_collision"].std()),
               f"{ce:.3f}" if ce is not None else "--"]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    tex = "\n".join(lines)
    with open(os.path.join(MS_DIR, out), "w") as f:
        f.write(tex)
    print(f"[tab] {out}")
    return tex


def tab_compute(out="tab_compute.tex") -> str:
    rows = []
    for m in HEADLINE_METHODS:
        lat, wall = [], []
        for s in HEADLINE_SEEDS:
            d = agg.load_json(os.path.join(EVAL_DIR, run_name(m, s),
                                           "latency.json"))
            if d:
                lat.append(d["mean_ms"])
            t = agg.load_json(os.path.join(RUNS_DIR, run_name(m, s),
                                           "summary.json"))
            if t:
                wall.append(t["wall_time_s"] / 3600.0)
        if not lat:
            continue
        rows.append((METHOD_TEX[m], np.mean(lat), np.mean(wall)))
    lines = [
        "% auto-generated by proteus.analysis.tables",
        "\\begin{table}[!t]\\centering",
        "\\caption{Computational footprint: per-decision latency "
        "(single-thread CPU) and training wall time per run.}",
        "\\label{tab:compute}",
        "\\footnotesize\\begin{tabular}{lcc}",
        "\\toprule",
        "Method & Decision [ms] & Train [h] \\\\",
        "\\midrule",
    ]
    for name, l, w in rows:
        lines.append(f"{name} & {l:.2f} & {w:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    tex = "\n".join(lines)
    with open(os.path.join(MS_DIR, out), "w") as f:
        f.write(tex)
    print(f"[tab] {out}")
    return tex


def numbers_digest(cells, cells_unseen, heldout, inter, out="numbers.json"):
    """Headline numbers cited in the manuscript body."""
    num = {}
    auc = agg.auc_table(cells, "success")
    auc_c = agg.auc_table(cells, "collision")
    for m in cells.method.unique():
        a = auc[(auc.method == m) & (auc.fault_type == "macro")]
        c = auc_c[(auc_c.method == m) & (auc_c.fault_type == "macro")]
        num[f"auc_s_{m}"] = round(float(a["auc_success"].mean()), 4)
        num[f"auc_s_{m}_std"] = round(float(a["auc_success"].std()), 4)
        num[f"auc_c_{m}"] = round(float(c["auc_collision"].mean()), 4)
        g = cells[(cells.method == m) & (cells.sev_idx == 0)]
        num[f"sr_nominal_{m}"] = round(float(g["success"].mean()), 4)
        g = cells[(cells.method == m) & (cells.sev_idx == 6)]
        num[f"sr_s1_{m}"] = round(float(g["success"].mean()), 4)
    # paired test PROTEUS vs DR
    ca = agg.cell_means(cells[cells.method == "proteus"])
    cb = agg.cell_means(cells[cells.method == "dr"])
    if not ca.empty and not cb.empty:
        num["wilcoxon_proteus_vs_dr"] = agg.paired_test(ca, cb)
    # onset
    for m in ("dr", "proteus", "teacher"):
        stats = [agg.onset_stats(m, s) for s in HEADLINE_SEEDS]
        stats = [x for x in stats if x]
        if stats:
            cw = np.mean([np.mean([st[ft]["collision_within_5s"]
                                   for ft in st]) for st in stats])
            sc = np.mean([np.mean([st[ft]["success"] for ft in st])
                          for st in stats])
            num[f"onset_coll5s_{m}"] = round(float(cw), 4)
            num[f"onset_success_{m}"] = round(float(sc), 4)
    # identification
    ids = [agg.identification_stats("proteus", s) for s in HEADLINE_SEEDS]
    ids = [x for x in ids if x]
    if ids:
        num["id_context_err"] = round(float(np.mean(
            [x["context_err"] for x in ids])), 4)
        num["id_cosine"] = round(float(np.mean([x["cosine"] for x in ids])), 4)
        r2s = {}
        for x in ids:
            for k, v in x["probe_r2"].items():
                if v is not None:
                    r2s.setdefault(k, []).append(v)
        num["id_probe_r2"] = {k: round(float(np.mean(v)), 4)
                              for k, v in r2s.items()}
    # unseen layout + heldout + intervention macro deltas
    if not cells_unseen.empty:
        for m in ("dr", "proteus", "teacher"):
            g = cells_unseen[cells_unseen.method == m]
            if not g.empty:
                num[f"unseen_sr_{m}"] = round(float(g["success"].mean()), 4)
    if not heldout.empty:
        for tag in ("deadzone", "latency+slip", "gain_L+bias", "encoder"):
            for m in ("dr", "proteus", "abl_noflow"):
                g = heldout[(heldout.method == m) &
                            (heldout.fault_type == tag) &
                            (heldout.severity > 0.5)]
                if not g.empty:
                    num[f"heldout_{tag}_{m}"] = round(
                        float(g["success"].mean()), 4)
    if not inter.empty:
        gi = inter[inter.method == "proteus"]
        gl = cells[(cells.method == "proteus")]
        hi = gi[gi.severity > 0.5]["success"].mean()
        hl = gl[gl.severity > 0.5]["success"].mean()
        num["intervention_sr_drop"] = round(float(hl - hi), 4)
    path = os.path.join(MS_DIR, out)
    with open(path, "w") as f:
        json.dump(num, f, indent=2)
    with open(os.path.join(EVAL_DIR, out), "w") as f:
        json.dump(num, f, indent=2)
    print(f"[numbers] {path}")
    return num
